In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [3]:
#Dimensions of the array
np.ndim(A)

1

In [4]:
A.shape #Return a tuple

(4,)

In [5]:
A.shape[0]

4

In [6]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

In [9]:
A=np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [10]:
B=np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [11]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [15]:
np.dot(B,A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [13]:
A=np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [14]:
B=np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [16]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [17]:
C=np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [18]:
np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [19]:
np.dot(C,A)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
A=np.array([[1,2],[3,4],[5,6]])
A.shape

(3, 2)

In [25]:
B=np.array([7,8])
B.shape

(2,)

In [26]:
np.dot(A,B)

array([23, 53, 83])

In [27]:
#scala product in neural network
X=np.array([1,2])
X.shape

(2,)

In [28]:
W=np.array([[1,3,5],[2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [29]:
W.shape

(2, 3)

In [30]:
Y=np.dot(X,W)
print(Y)

[ 5 11 17]
