In [1]:
import numpy as np

In [2]:
a = np.array([0.3,2.9,4.0])

In [3]:
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [5]:
y = exp_a/sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [6]:
#implement softMax function 

def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    
    return y

In [7]:
a = np.array([1010, 1000, 900])
np.exp(a)/np.sum(np.exp(a))

C:\Users\nrtak\AppData\Local\Temp\ipykernel_26488\2995076072.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a)/np.sum(np.exp(a))
C:\Users\nrtak\AppData\Local\Temp\ipykernel_26488\2995076072.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a)/np.sum(np.exp(a))


array([nan, nan, nan])

In [8]:
c = np.max(a)
a-c

array([   0,  -10, -110])

In [9]:
np.exp(a-c)/np.sum(np.exp(a-c))

array([9.99954602e-01, 4.53978687e-05, 1.68883521e-48])

In [10]:
#Softmax function improves overflow problem
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    
    return y

In [11]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [12]:
np.sum(y)

1.0